---
title: "R Notebook"
output: html_notebook
author: "Yuting Qiu"
date: "2020_03_23"
---
Description: here we only use the raw mean for analysis, because it has a higher heritibility rate
              I am thinking about doing TBBC3 2018 and 2019 sepetately. 

              
```{r}
# remove all the variables
rm(list = ls())
```


```{r}
# read in dataset
est_tbbc3_18 <- read.csv("/Users/qiuyuting/Documents/data_file/est_tbbc3_18.csv", header = TRUE)
est_tbbc3_19 <- read.csv("/Users/qiuyuting/Documents/data_file/est_tbbc3_19.csv", header = TRUE)
est_z025_19 <- read.csv("/Users/qiuyuting/Documents/data_file/est_z025_19.csv", header = TRUE)
est_tbbc3_1819 <- read.csv("/Users/qiuyuting/Documents/data_file/est_tbbc3_1819.csv", header = TRUE)
est_tbbc3_1819 <- est_tbbc3_1819[,-1]
```

# show the correlation table
```{r}
library(corrplot)
colnames(est_tbbc3_18)[1] <- "genotype"
round(cor(est_tbbc3_18[,-1]),2)

colnames(est_tbbc3_19)[1] <- "genotype"
round(cor(est_tbbc3_19[,-1]),2)

colnames(est_z025_19)[1] <- "genotype"
round(cor(est_z025_19[,-1]),2)

colnames(est_tbbc3_1819)[1] <- "genotype"
round(cor(na.omit(est_tbbc3_1819[,-1])),2)

pairs(est_tbbc3_18[,-1])
pairs(est_tbbc3_19[,-1])
pairs(est_z025_19[,-1])
pairs(est_tbbc3_1819[,-1])
```


# 2018 TBBC3 population PCA analysis
```{r}
# 2018 all info in, without new variables
PCA_tbbc3_18 <- princomp(est_tbbc3_18[,-c(1,5,6)], cor = T, scores = T) #cor equals T means use the correlation matrix
summary(PCA_tbbc3_18)
# One PC would be enough

loadings(PCA_tbbc3_18) # positively correlated
biplot(PCA_tbbc3_18)
```

# examine the normality of the PCA scores
```{r}
tbbc3_18_scores <- PCA_tbbc3_18$scores[,1]
boxplot(est_tbbc3_18$mean)
boxplot(tbbc3_18_scores) # some outliers, but much better than the old one, and there are sone check lines 
shapiro.test(est_tbbc3_18$mean)
shapiro.test(tbbc3_18_scores) # not quite normal
library(ggpubr)
ggqqplot(tbbc3_18_scores)
```

## Z025 population in 2019
```{r}
PCA_z025_19 <- princomp(est_z025_19[,-c(1,5,6,8)], cor = T, scores = T)
summary(PCA_z025_19) # alomost need 2 pc, but one PC would be fine
PCA_z025_19$loadings # mummirate and severity can see some opposite direction 
PCA_z025_19$sdev ^ 2
biplot(PCA_z025_19)

z025_19_scores <- PCA_z025_19$scores[,1]
boxplot(z025_19_scores) # looks nice
shapiro.test(z025_19_scores) # much better
ggqqplot(z025_19_scores) # nice
```

# TBBC3 population 2019 dataset
```{r}
PCA_z025_19 <- princomp(est_tbbc3_19[,-c(1,5,6,8)], cor = T, scores = T)
summary(PCA_z025_19) # need two PC here
unclass(PCA_z025_19$loadings)
PCA_z025_19$sdev ^ 2
biplot(PCA_z025_19)

tbbc3_19_scores <- PCA_z025_19$scores[,1:2]
boxplot(tbbc3_19_scores)
shapiro.test(tbbc3_19_scores[,1]) #almost normal
shapiro.test(tbbc3_19_scores[,2]) # quite unnormal
ggqqplot(tbbc3_19_scores[,1])
ggqqplot(tbbc3_19_scores[,2])
```


# TBBC3 population 2019 dataset, without mummified
```{r}
PCA_z025_19.1 <- princomp(est_tbbc3_19[,-c(1,4,5,6,8)], cor = T, scores = T)
summary(PCA_z025_19.1) # need 1 PC here
unclass(PCA_z025_19.1$loadings)
PCA_z025_19.1$sdev ^ 2
biplot(PCA_z025_19.1)
# severity show sometthing opposite

tbbc3_19_scores.1 <- PCA_z025_19.1$scores[,1]
boxplot(tbbc3_19_scores.1)
shapiro.test(tbbc3_19_scores.1) #almost normal
ggqqplot(tbbc3_19_scores.1)
```


# TBBC3 populaiton 2018 2019 data combined
```{r}
PCA_tbbc3_1819 <- princomp(na.omit(est_tbbc3_1819[,-c(1,3,6)]), cor = T, scores = T)
summary(PCA_tbbc3_1819) # almost 1 pc
unclass(PCA_tbbc3_1819$loadings) # still, severity show somethig opposite

PCA_tbbc3_1819$scores[,1] -> tbbc3_1819_scores
boxplot(tbbc3_1819_scores)
shapiro.test(tbbc3_1819_scores)
ggqqplot(tbbc3_1819_scores)
```

